# Generated by Django 2.1.2 on 2018-10-07 03:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('calories', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('vegetarian', models.BooleanField()),
                ('gluten_free', models.BooleanField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
