# Generated by Django 2.1.2 on 2018-10-08 04:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.CharField(default='Entrada', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='price',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
